export let ALL_FILES = [];
export let sessionNote = '';
export let projectLog = [];
export let _noteSaveTimer = null;
export let currentFolder = null;
export let fileView = 'list';
export let ctxEl = null;
export let projects = [];
export let currentSort = 'date';
export let activeFilters = new Set();
export let galleryFilter = 'all';
export let galleryView = 'grid';
export let galCalView = 'month';
export let galCalYear = new Date().getFullYear();
export let galCalMonth = new Date().getMonth();
export let galCalDay = new Date().getDate();
export let _galCalDateTarget = -1;
export let thumbTargetIdx = null;
export let globalSettings = { root_path: '', blender_path: '', painter_path: '', unity_path: '', bases_path: '' };

export function setAllFiles(v) { ALL_FILES = v; }
export function setProjects(v) { projects = v; }
export function setGlobalSettings(v) { globalSettings = v; }
export function setCurrentFolder(v) { currentFolder = v; }
export function setFileView(v) { fileView = v; }
export function setCurrentSort(v) { currentSort = v; }
export function setActiveFilters(v) { activeFilters = v; }
export function setSessionNote(v) { sessionNote = v; }
export function setProjectLog(v) { projectLog = v; }
export function setGalleryFilter(v) { galleryFilter = v; }
export function setGalleryView(v) { galleryView = v; }
export function setGalCalView(v) { galCalView = v; }
export function setGalCalYear(v) { galCalYear = v; }
export function setGalCalMonth(v) { galCalMonth = v; }
export function setGalCalDay(v) { galCalDay = v; }
export function setGalCalDateTarget(v) { _galCalDateTarget = v; }
export function setThumbTargetIdx(v) { thumbTargetIdx = v; }
export function setCtxEl(v) { ctxEl = v; }
